### ISSUE TITLE
v4.2.0 causes infinite redirects & does not recognise HTTPS 🐛 

### ISSUE THREAD

**Issue by JV-conseil** [django-cas-ng/django-cas-ng#289]
**Platform & Version**

- Platform: MacOS High Sierra 10.13.6
- django-cas-ng: 4.2.0
- Django: 3.2.4
- Python: 3.8.10
- CAS Server Software and version: CASClientV2
- Cloud Platform: Azure WebApps

**Describe the bug**

- `/accounts/login/?next=` uri segment gets replicated indefinitely.
- the browser indicates the connection is not secured (not HTTPS).

**To Reproduce**

Not available.

I've activated & deactivated one by one, the following `settings` lines, with no positive effect on the problem:

- SECURE_SSL_REDIRECT = True
- SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
- CAS_FORCE_SSL_SERVICE_URL = ONLINE

**Expected behavior**
\-

**Screenshots**

![django-cas-ng v4 2 0 causes infinite redirects   do not recognise HTTPS](https://user-images.githubusercontent.com/8126807/120854001-c6fcb980-c57c-11eb-9276-7f25ca0df95b.png)

**Additional context**

```py
settings.py

SECURE_SSL_REDIRECT = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SESSION_COOKIE_SECURE = True
SESSION_COOKIE_SAMESITE = 'None' if SESSION_COOKIE_SECURE is True else 'Lax'
CSRF_COOKIE_SECURE = SESSION_COOKIE_SECURE
CSRF_COOKIE_SAMESITE = SESSION_COOKIE_SAMESITE
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

...

CAS_SERVER_URL = 'https://...'
CAS_FORCE_SSL_SERVICE_URL = ONLINE
CAS_APPLY_ATTRIBUTES_TO_USER = True
```

**Temporary Workaround**

Go back to `django-cas-ng v4.1.1`

```txt
requirements.txt

django-cas-ng==4.1.1
```

**Comment by KenWhitesell** [comment]
Try either setting CAS_ADMIN_REDIRECT = False _or_ CAS_ADMIN_PREFIX to the appropriate value.

The issue appears to be in middleware.py at the very end of process_view. There are a set of tests that check the value of view_func.

The first test is `if view_func == login`, where `login` is `django.contrib.auth.views.LoginView`. However, in our case, we use a custom LoginView, and so this test fails for us.

Further down in the method, version 4.1.1 has this block of code:
`
    if settings.CAS_ADMIN_PREFIX:
        if not request.path.startswith(settings.CAS_ADMIN_PREFIX):
            return None
    elif not view_func.__module__.startswith('django.contrib.admin.'):
        return None
`
Since our view_func class isn't in django.contrib.admin, this test fails and so the method returns None at this point. 

That test was rewritten for 4.2 as:
`
        if settings.CAS_ADMIN_REDIRECT:
            if settings.CAS_ADMIN_PREFIX:
                if not request.path.startswith(settings.CAS_ADMIN_PREFIX):
                    return None
                elif not view_func.__module__.startswith('django.contrib.admin.'):
                    return None
        else:
            return None
`
This test will fall through if CAS_ADMIN_REDIRECT is "truthy" and CAS_ADMIN_PREFIX is "falsy". The default values in `__init__.py` match these conditions. 

(I can't say as I understand the reason behind why these conditionals are written like this, so I can say I know what should be done to resolve this. It's possible that an `else: return None` at the same level as the `if settings.CAS_ADMIN_PREFIX` _might_ be a solution, but I don't know.)
